Update README.md
invest-ex/chart_module pull request #1
Opened 2019-04-17 19:28 UTC by carl12

2019-04-17 22:23 UTC, MarissaShieh requested changes

2019-04-17 22:23 UTC, MarissaShieh commented on README.md
>  ### Installing Dependencies
It may make sense to move this section above the Usage section.

2019-04-17 22:23 UTC, MarissaShieh commented on README.md
> +PUT | api/chart/:stock-id/info/noOfOwners | Set new number of owners | Num | None
Why did you choose to have PUT endpoints for these but not for the other data like related tags, etc?

2019-04-18 02:58 UTC, carl12 commented on README.md
> +PUT | api/chart/:stock-id/info/noOfOwners | Set new number of owners | Num | None
Good point, I have condensed my put requests into one request which overwrites the entire object. Updates to tags should be infrequent, so it makes sense to focus on other functionality.

2019-04-18 02:58 UTC, carl12 commented on README.md
>  ### Installing Dependencies
Good suggestion, readme is updated.

2019-04-18 03:02 UTC, MarissaShieh approved these changes

2019-04-18 03:04 UTC, MarissaShieh commented
This looks good to go!

2019-04-18 03:04 UTC, merged